### ISSUE TITLE
nn.parallel.DistributedDataParallel

### ISSUE THREAD

**Issue by elikarimi** [cellimnet/microsnoop-publish#1]
Hi cellimnet team, 

Thank you for sharing your microsnoop repo with the world. We are trying to run the inference on the cyclops data on 4 GPUs of RTX 4090s and our processes freeze on line 71 of modelzoo.py (where nn.parallel.DistributedDataParallel is called). Apparently, this is a very known issue of p2p connection on the family of XX90s GPUs and one fix that is suggested is to disable NCCL P2P connection (export NCCL_P2P_DISABLE=1). We tried this and we got the following error:

embedding = embed_fn(latent)
TypeError: 'NoneType' object is not callable

We also tried hiding the other available GPUs and still got the same error. Do you run this on a single or cluster of 3090s (as you report on the readme page) and if yes, do you have any issues like the one we faced and do you know how we can possibly resolve this issue by any chance? Any help would be enormously appreciated.

**Comment by cellimnet** [comment]
Hi elikarimi:
	Thanks for using our representation tool Microsnoop. We have validated our repo on 4 GPUs of NVIDIA T4 Tensor Core GPU (AWS instance type: g4dn.12xlarge) while we did not face your issue. According to your description, we suggest you to check in the following steps:
1.	Ensure the images are read correctly and are embedded by the model (according to the TypeError, we guess the images were not correctly embedded to latent embeddings).
2.	You can try using single GPU through replacing the value of args.ngpu with 1 in eval.py line 122, to avoid the effect of nGPUs.
We look forward to your further feedback.
