### ISSUE TITLE
How to access training datasets?

### ISSUE THREAD

**Issue by kian-kd** [cellimnet/microsnoop-publish#2]
Hello, 

I recently read your paper on Microsnoop and found it very interesting and inspiring - amazing work!

I'm looking to try reproducing your results and retraining the CNN and ViT model.

[In your paper](https://www.biorxiv.org/content/10.1101/2023.02.25.530004v4.full.pdf), you describe that training set details are in "Supplementary Table 1", but I don't actually see that table (or Table 2) in the paper. So the issue is: **Supplementary Tables 1 and 2 are missing from your paper**.

Can you please tell me the best and quickest way I can download / procure the training dataset?

**Comment by kian-kd** [comment]
Nevermind, I didn't realize the tables were with the paper:
https://www.biorxiv.org/content/10.1101/2023.02.25.530004v4.supplementary-material

Have a great day!

**Comment by cellimnet** [comment]
Haha，we apologize for the delay in answering your question. Thank you for using our Microsnoop.
