### ISSUE TITLE
Question about which version of the NuCLS dataset was used in training

### ISSUE THREAD

**Issue by MaryFllh** [cellimnet/microsnoop-publish#3]
Hello, 

I noticed that there are single rater and multi rater data available on https://sites.google.com/view/nucls/home. I was wondering which one did you use. Within each there seems to be different subsets, e.g. corrected, uncorrected. If you can verify which rgb images you used it will be very helpful! 

Thank you!

**Comment by cellimnet** [comment]
Hi,

We downloaded the images of NuCLS from https://drive.google.com/drive/folders/1IyFVpB87VnX1Xjshyoj9TfpwPgTdorcF. And we noticed that they have deleted one image compared with the version we downloaded, this image is significantly smaller than the others, we provided it as following and you can decide how to use it :

![TCGA-A2-A0CM-DX1_id-5ea40963ddda5f8398979473_left-20308_top-57208_bottom-57233_right-20331](https://user-images.githubusercontent.com/53943533/233513598-d30c17aa-d2d5-47a5-99b8-c86c54b1180d.png)

The final NuCLS dataset we used in training is 1745 images, and we random split it into training and validation set.

**Comment by MaryFllh** [comment]
Thank you so much for the clarification.
